# A generic, single database configuration.

[alembic]
# path to migration scripts
script_location = alembic

# template used to generate migration files
# file_template = %%(rev)s_%%(slug)s

# sys.path path, space-separated, needed to import models
prepend_sys_path = .

# timezone to use when rendering the date within the migration file
# timezone =

# version location specification; This defaults
# to alembic/versions.  When using multiple version
# directories, directories are separated by a space.
# version_locations = %(here)s/alembic/versions

# logging configuration; if present, it is used
# logger_alembic = INFO

[logging]
# logging configuration
# logger_root = INFO
# logger_sqlalchemy = WARN
# logger_alembic = INFO
